version: '3.8'
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=root
    - PUID=1000
    - PGID=1000
    volumes:
    - ./mongo_data:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped